services:
  web:
    image: dniamsaard4codework/st126235_car_price_app:a2.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: a2-car-price-predictor
    ports:
      - "8050:8050"                   # host:container
    environment:
      - HOST=0.0.0.0
      - PORT=8050
      - DEBUG=False
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      # INSIDE the container your app listens on 8050, not 80
      test: ["CMD", "curl", "-f", "http://localhost:8050/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - car-price-network

networks:
  car-price-network:
    driver: bridge